@ASPNet8API_HostAddress = https://localhost:7243

GET {{ASPNet8API_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{ASPNet8API_HostAddress}}/weatherforecast

###

GET {{ASPNet8API_HostAddress}}/api/superhero

###
